### ISSUE TITLE
No fucks given on basic git commands

### ISSUE THREAD

**Issue by SirWrexes** [oh-my-fish/plugin-thefuck#10]
Hello,
I get no fucks given when I fuckup "branch" or this sort of stuff, but not if I do something like gti.
Thanks. 

![screenshot_20181104_012248](https://user-images.githubusercontent.com/5567164/47958683-5e1dc100-dfd0-11e8-8f80-e872351a03d3.png)

**Comment by asfaltboy** [comment]
I have the same issue. I tried updating to latest version of thefuck (as well as the omf plugin-thefuck). I see this:
```
$ git brch
git: 'brch' is not a git command. See 'git --help'.

The most similar command is
	branch

$ fuck
Nothing found
```

It's also super slow at that (3.8s for the above fail) .

@oh-my-fish @scorphus @bobthecow any ideas?

**Comment by asfaltboy** [comment]
btw, it seems it always happen with fish, but not with bash, even if I don't use thefuck plugin (but just manually set fish integration as per thefuck docs). Oooh! Right as I was about to open a ticket @ nvbn/thefuck I see nvbn/thefuck#727 and of course I have hub aliased to git 🤦‍♂️ !

This worked for me just fine: `set -x THEFUCK_OVERRIDDEN_ALIASES 'git'`

Reference: https://github.com/nvbn/thefuck/wiki/Shell-aliases#fish

**Comment by SirWrexes** [comment]
I didn't make any alias for git, so sadly this changed nothing. 
![screenshot_20190305_152104](https://user-images.githubusercontent.com/5567164/53811840-80adef80-3f5a-11e9-9079-41a3682164c0.png)

**Comment by asfaltboy** [comment]
Sure you haven't installed [hub][1]?

Either way, try running the command with `THEFUCK_DEBUG=true` e.g:

    THEFUCK_DEBUG=true thefuck git brnch master

And if that doesn't give you enough to go on, open a ticket [with thefuck][2].

[1]: https://hub.github.com/
[2]: https://github.com/nvbn/thefuck/issues/new

**Comment by scorphus** [comment]
Also, it would be helpful to know the output of `thefuck --version`. Can you please post it? Thanks!

**Comment by SirWrexes** [comment]
Hey,
So I just checked, I don't have hub installed. Also I'm using The Fuck 3.15 with Python 3.6.8. Lastly, here's [a gist](https://gist.github.com/fox-tek/75e0e4d9134c7233dfb2d2490bf3bef6) with the output of thefuck with debug on.
Thanks.

**Comment by SirWrexes** [comment]
On a side note for peoploe having the same issue: 
I have set up help.autocorrect in my `.gitconfig`. It basically does the same thing and automatically inputs the right command after a delay you choose in the configuration. Nevertheless, I still prefer thefuck as I think it's simpler, prettier and more powerful. The fact that you have to hit enter to confirm you want to unfuck your command is also better IMO.

**Comment by scorphus** [comment]
@fox-tek, 3.15 is quite old. Can you please update it to 3.28?

Regarding your side note (and also the gist) that `help.autocorrect` config directive is forbidding TheFuck from correctly matching the output against the `git_not_command` rule. See:

![image](https://user-images.githubusercontent.com/2112697/55191079-89809280-51a1-11e9-9370-afe48052079e.png)

I know your previous messages were taken when `help.autocorrect` was not enabled. So this is just a reminder for you to turn it of when you'll test it again.

After you update to latest version 3.28 let us know if the issue persists.

**Comment by SirWrexes** [comment]
Okay so I found out dnf only has 3.15 as its latest.

I did a clean pip3 install with `get-pip.py` (because it was having some conflicts, too),
Installed thefuck with python3.
Reinstalled omf thefuck plugin just to be sure.
Ran `thefuck --alias > /home/_usrname_/.config/fish/functions/fuck.fish`
It works ! Now I can happily curse when I miss a git command.

Hope this can help other Fedora user that might have tried installing it with dnf
And again, thanks for the support.

Unrelated quickie : I like your prompt's colours quite a lot. Also what font are you using ?

**Comment by scorphus** [comment]
Great! So glad latest version works! I'll go ahead and close this issue.

Bear in mind that manually setting the `fuck` function the way you did rules out this plugin, whose purpose is to keep the function always up to date in a dynamic and efficient way. You can keep that function and uninstall the plugin – for it is unnecessary in such case – but always remember to update the function whenever TheFuck gets updated.

I'm using the [Fira Code](/tonsky/FiraCode) font. Those colors are from the dark variation of [themer-colors-one](/mjswensen/themer/tree/master/cli/packages/themer-colors-one) terminal theme I generated using [themer](/mjswensen/themer). And last but not at all least, the Oh My Fish theme I use is [scorphish](/oh-my-fish/theme-scorphish) 🙂

So I'm closing this one. Please feel free to reopen it in case it's still an issue.

**Comment by SirWrexes** [comment]
I should have then mentioned that without setting up the alias function, thefuck only printed on stdout the command rather than executing it. I'll test it sometime to be sure it wasn't just me doing something wrong and come back to comment about it.

**Comment by SirWrexes** [comment]
So apparently it happened only once, or maybe I just read wrong. I moved fuck.fish outside of the functions dir and it still works fine.
Everything's ok.
