### ISSUE TITLE
Hangs on startup

### ISSUE THREAD

**Issue by scorphus** [oh-my-fish/plugin-thefuck#11]
The plugin forbids the shell to even initiate. Then memory consumption rockets.

If you experience this problem deactivate the plugin temporarily, until it gets fixed:

```fish
rm -rf ~/.local/share/omf/pkg/thefuck
```

**Comment by scorphus** [comment]
Will be fixed on next [TheFuck](/nvbn/thefuck) release, 3.29.

**Comment by 0rvar** [comment]
Use `thefuck --alias | source` in your fish config instead of this plugin

**Comment by scorphus** [comment]
The whole point of this plugin is saving startup time. If you add that to you `config.fish`, it will work, certainly. But for every new tab or window (i.e. every new Fish session that you create) a significant amount of time will be spent setting up the `fuck` function. This plugin does that in **2%** of the time.

**Comment by 0rvar** [comment]
> This plugin does that in **2%** of the time.

Well, it would do that if it worked instead of hanging

**Comment by scorphus** [comment]
> Well, it would do that if it worked instead of hanging

Indeed. This is very true.

**Comment by scorphus** [comment]
This is solved with just released [TheFuck 3.29](https://pypi.org/project/thefuck/3.29/).
