### ISSUE TITLE
Major issue - hangs process and fills up PC memory

### ISSUE THREAD

**Issue by MostHated** [oh-my-fish/plugin-thefuck#13]
I tried to use this and it just makes the shell hang and then proceeds to use up all system memory. You can see here where I forced closed it when testing.

![](https://i.imgur.com/zcZJCJX.png)

**Comment by 0rvar** [comment]
Use `thefuck --alias | source` in your fish config instead of this plugin

**Comment by scorphus** [comment]
Dupe of #11. Fixed in [TheFuck 3.29](https://pypi.org/project/thefuck/3.29/).
