### ISSUE TITLE
Not working after install

### ISSUE THREAD

**Issue by benmarten** [oh-my-fish/plugin-thefuck#2]
Getting this issue after install in the fish shell:

```
$(...) is not supported. In fish, please use '(thefuck)'.
- (line 1): begin; function fuck --wraps TF_ALIAS=fuck;  TF_ALIAS=fuck eval $(thefuck (fc -ln -1)) $argv; end 
                                                                            ^
from sourcing file -
    called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
    called on line 69 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/alias.fish

in function 'alias'
    called on line 16 of file ~/.config/fish/config.fish
    with parameter list 'fuck=TF_ALIAS=fuck eval $(thefuck (fc -ln -1))'

from sourcing file ~/.config/fish/config.fish
    called during startup
```

Changing:
`alias fuck='TF_ALIAS=fuck eval $(thefuck $(fc -ln -1))'`
to:
`alias fuck='TF_ALIAS=fuck eval $(thefuck (fc -ln -1))'`
in `~/.config/fish/config.fish` fixed it for me... Is this an issue within thefuck or within this wrapper plugin?

**Comment by scorphus** [comment]
I guess `fuck` alias in your `~/.config/fish/config/fish` is overriding the function declared by the plugin. What is the output of the following?

``` fish
functions fuck
```

Either you choose to use the alias or the plugin.

**Comment by scorphus** [comment]
Hello, @benmarten. Any news on this front?

**Comment by benmarten** [comment]
I just reinstalled everything. The problem seems gone. Everything works right out of the box! Thx.
