### ISSUE TITLE
Always gives response "No fucks given"

### ISSUE THREAD

**Issue by devert** [oh-my-fish/plugin-thefuck#6]
Using Fish version 2.4.0, Oh My Fish version 3 and thefuck version 3.11 on OSX Yosemite. Installed thefuck via homebrew and it works correctly when using Bash. However, when installing the plugin with OMF and trying to use with fish, it only ever responds with "No fucks given."

**Comment by scorphus** [comment]
Hi! Let's try and make it work for you!

What is the output of each of the following commands?

- `thefuck echoo ok`
- `omf list`
- `functions fuck`
- `functions __tf_alias`
- `functions __tf_updt`
- `echo $__tf_func`
- `echo $__tf_vers`

Thanks!

**Comment by devert** [comment]
Hi @scorphus. Here is the output of each of the commands:

* ```thefuck echoo ok```

   ```echo ok [enter/↑/↓/ctrl+c]```

* ```omf list```
  * Plugins: brew, composer, fish-spec, foreign-env, git-flow, nvm, omf, thefuck
  * Themes: default
* ```functions fuck```

  ```
  function fuck --description 'Correct your previous console command'
     __tf_alias
    fish -c __tf_updt 2>&1 > /dev/null &
  end
  ```
* ```functions __tf_alias```
  
  ```
  function __tf_alias --description 'Correct your previous console command'
        set -l fucked_up_command $history[1];  env TF_ALIAS=__tf_alias PYTHONIOENCODING=utf-8 thefuck $fucked_up_command | read -l unfucked_command;  if [ "$unfucked_command" != "" ];    eval $un
  fucked_command;    history --delete $fucked_up_command;    history --merge ^ /dev/null;  end;
  end
  ```
* ```functions __tf_updt```

  ```
  function __tf_updt
        set -l tf_vers (thefuck -v 2>&1)
    if test "$__tf_vers" != "$tf_vers" -o -z "$__tf_func"
      set -U __tf_vers $tf_vers
      set -U __tf_func (thefuck -a "__tf_alias" | tr "\n" ";")
      eval $__tf_func
    end
  end
  ```
* ```echo $__tf_func```

```
function __tf_alias -d "Correct your previous console command";  set -l fucked_up_command $history[1];  env TF_ALIAS=__tf_alias PYTHONIOENCODING=utf-8 thefuck $fucked_up_command | read -l unfucke
d_command;  if [ "$unfucked_command" != "" ];    eval $unfucked_command;    history --delete $fucked_up_command;    history --merge ^ /dev/null;  end;end;
```

* ```echo $__tf_vers```

  ``` The Fuck 3.11 using Python 2.7.10```

Thank **you** good sir.

**Comment by scorphus** [comment]
Hey, @devert! Thank you for posting the outputs!

I still see no clear reason why it doesn't work. I also tried to reproduce it in my Mac OS X with no success.

_Before we move forward_, how about we create another alias – say, `fuckey` – and see if it works?

- Create a new alias:
```fish
⋊> ~ eval (thefuck --alias fuckey | tr '\n' ';')
⋊> ~ functions fuckey
function fuckey --description 'Correct your previous console command'
	set -l fucked_up_command $history[1];  env TF_ALIAS=fuckey PYTHONIOENCODING=utf-8 thefuck $fucked_up_command | read -l unfucked_command;  if [ "$unfucked_command" != "" ];    eval $unfucked_command;    history --delete $fucked_up_command;    history --merge ^ /dev/null;  end;
end
```
- Test it:
```fish
⋊> ~ echoo ok
fish: Unknown command 'echoo'
⋊> ~ fuckey
echo ok [enter/↑/↓/ctrl+c]
ok
⋊> ~ 
```

Does it work this way?

Thanks!

**Comment by devert** [comment]
Hi @scorphus.

So before even creating the alias, I tried just your example of ```echoo ok``` and got the expected result. What doesn't seem to work for me is, for example, ```git brnch```. Rather than providing a fix to ```git branch``` it says ```No fucks given```. After creating the ```fuckey``` alias, I get the same result of ```No fucks given```. As I said before, if I switch back to bash it works correctly oddly enough.

**Comment by scorphus** [comment]
Hey!

I think you may have `git` aliased to another command. Is this the case? If so, adding the following line to your `config.fish` might solve it:

```fish
# Comma-separated overridden aliases for TheFuck
set -xg THEFUCK_OVERRIDDEN_ALIASES 'git'
```

Thanks!

**Comment by devert** [comment]
@scorphus You are totally correct. I have git aliased to the "hub" command for this command-line wrapper (https://hub.github.com/). Your ```config.fish``` setting has made things work correctly. Thanks for the help!
