### ISSUE TITLE
usage: basename string [suffix] while unfucking

### ISSUE THREAD

**Issue by brunobbbs** [oh-my-fish/plugin-thefuck#7]
```
> echoo ok
fish: Unknown command 'echoo'
> fuck
echo ok [enter/↑/↓/ctrl+c]
ok
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
> 
```

fish, version 2.5.0

**Comment by scorphus** [comment]
Hey, chap! Is this still an issue? Also, there's no `basename` calls in the plugin or TheFuck or in itself.

So, I'm closing it for now. We reopen it if it's still an issue.
